# Generated by Django 6.1 on 2026-09-04 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id_ejercicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=100)),
                ('tipo_ejercicio', models.CharField(max_length=100)),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gimnasio',
            fields=[
                ('id_gimnasio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_gym', models.CharField(max_length=150)),
                ('ubicacion_gym', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('id_instructor', models.IntegerField(blank=True, null=True)),
                ('nombre_rutina', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('frecuencia_semanal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRutina',
            fields=[
                ('id_detalle_rutina', models.AutoField(primary_key=True, serialize=False)),
                ('orden_ejercicio', models.CharField(blank=True, max_length=50, null=True)),
                ('series_asignadas', models.IntegerField(default=0)),
                ('repeticiones_asignadas', models.IntegerField(default=0)),
                ('carga_asignada', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_descanso', models.CharField(blank=True, max_length=50, null=True)),
                ('lado', models.CharField(blank=True, max_length=50, null=True)),
                ('id_ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_rutina', to='gimnasioapp.ejercicio')),
                ('id_rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gimnasioapp.rutina')),
            ],
        ),
        migrations.CreateModel(
            name='SesionEntrenamiento',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('id_rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='gimnasioapp.rutina')),
            ],
        ),
        migrations.AddField(
            model_name='rutina',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas', to='gimnasioapp.usuario'),
        ),
    ]
