# Generated by Django 6.1 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gimnasioapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='sesionentrenamiento',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
