# Generated by Django 6.1 on 2026-09-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(default='', max_length=100)),
                ('ubicacion', models.CharField(default='', max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(default='', max_length=100, unique=True)),
                ('estado_equipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.TextField()),
                ('descripcion_problema', models.TextField()),
                ('fecha_mantenimiento', models.DateField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
    ]
