# Generated by Django 6.1.1 on 2026-09-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Sesion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='fecha_adquisicion',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='id',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='ultimo_mantenimiento',
        ),
        migrations.AddField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_equipo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='equipo',
            name='id_gimnasio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipo',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquina.equipo'),
        ),
    ]
